name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Update and install Python if needed
            sudo apt update
            sudo apt install -y python3 python3-venv python3-pip git

            # Stop any existing Flask app
            pkill -f app.py || true

            # Deploy new code
            rm -rf ~/flaskapp
            mkdir ~/flaskapp
            cd ~/flaskapp
            git clone https://github.com/apz-ns/devopswithaiman.git .
            
            # Create virtual environment
            python3 -m venv venv
            source venv/bin/activate

            # Install dependencies inside venv
            pip install --upgrade pip
            pip install -r requirements.txt

            # Start Flask in background
            nohup venv/bin/python app.py --host=0.0.0.0 --port=5000 > app.log 2>&1 &
          EOF

