name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            pkill -f app.py || true
            rm -rf ~/flaskapp
            mkdir ~/flaskapp
            cd ~/flaskapp
            git clone https://github.com/apz-ns/devopswithaiman.git .
            sudo apt update
            sudo apt install python3-pip -y
            pip3 install -r requirements.txt
            nohup python3 app.py > app.log 2>&1 &
          EOF

